<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Barang</name>
   <tag></tag>
   <elementGuidId>bc54908a-5432-47ef-b3f5-7a3a978978bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.add_field_button.btn.btn-info.btn-xl.js-scroll-trigger.mb-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tambah Barang&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c8f7dc2-5b59-4756-855a-9d2dae5c1ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4a70c11-f578-4fb7-bedd-38ff6a22754b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_field_button btn btn-info btn-xl js-scroll-trigger mb-3</value>
      <webElementGuid>cce9bd88-b229-4685-8a29-aa20d64ccc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Barang</value>
      <webElementGuid>ce608534-473d-47e9-b1ce-8d3b7fcb46a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;online&quot;)/div[@class=&quot;container&quot;]/form[1]/div[@class=&quot;input_fields_wrap&quot;]/center[1]/button[@class=&quot;add_field_button btn btn-info btn-xl js-scroll-trigger mb-3&quot;]</value>
      <webElementGuid>40eac069-0748-41fe-b8cb-76a2feac71b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>70e1377d-0455-48a7-96b0-504d2ff3e7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='online']/div/form/div[2]/center/button</value>
      <webElementGuid>1920b1ce-5466-4c49-8bf8-9f39c0d63f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/following::button[1]</value>
      <webElementGuid>31566f28-cf11-4e2b-92e9-3333bb4c3409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga (per Hari)'])[1]/following::button[1]</value>
      <webElementGuid>32d070cf-a4ec-4d1e-97b1-a1ad999567f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Sewa'])[1]/preceding::button[1]</value>
      <webElementGuid>7effeb93-324f-47e7-80f9-86c6a488e345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lama Sewa (Hari)'])[1]/preceding::button[1]</value>
      <webElementGuid>f568e4c3-c9fe-4168-ab7a-4af48462d80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Barang']/parent::*</value>
      <webElementGuid>d922fbc3-134f-4aab-90ee-d35a1721c0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/button</value>
      <webElementGuid>a137c805-1bfb-4200-ab45-3783dd850c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tambah Barang' or . = 'Tambah Barang')]</value>
      <webElementGuid>4789c3d7-dd24-4aaa-9f84-6b82043a4d64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
