<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Pilih Barang--Carrier 35 Liter (20_44ae9c</name>
   <tag></tag>
   <elementGuidId>f66121c1-4b62-4ab7-8f72-533f9fce98ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@name='kode'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tambah2 > div.row > div.col-lg-6.col-sm-12 > div.form-group > select[name=&quot;kode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c2641d3f-9b23-499d-8b5a-4783ca3badd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kode</value>
      <webElementGuid>755f913d-5071-4a2c-a9d2-0b0134165c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c08ac9a8-398c-4e39-bca3-1fffc8c22bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>prosesBarang(this.value , 2)</value>
      <webElementGuid>2a0352d5-df28-4ebb-b60b-abf964553871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Pilih Barang--Carrier 35 Liter (20 unit)Carrier 45 Liter (19 unit)Carrier 60 Liter (23 unit)Carrier 80 Liter (10 unit)Kompor Besar (8 unit)Headlamp (50 unit)Lampu Tenda (29 unit)Nesting (63 unit)Kompor Portable Mini (17 unit)Gas HiCook (110 unit)Sepatu Tinggi Size 40 (10 unit)Sepatu Tinggi Size 41 (15 unit)Sepatu Tinggi Size 43 (15 unit)Sepatu Tinggi Size 42 (10 unit)Tas Slempang (15 unit)Tenda Kapasitas 2-3 Orang (60 unit)Tenda Double Layer Kapasitas 4-5 Orang (26 unit)Tenda Single Layer 4-5 Orang (17 unit)Tenda Kapasitas 7-8 Orang (15 unit)Tenda Kapasitas 8-10 Orang (20 unit)Tracking Pole (30 unit)Sleeping Bag (46 unit)Matras (36 unit)</value>
      <webElementGuid>21a21f00-0ae7-400c-907c-b0e42ecbb929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;online&quot;)/div[@class=&quot;container&quot;]/form[1]/div[@class=&quot;input_fields_wrap&quot;]/div[@class=&quot;tambah2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>b4a0abbb-5193-48d3-b66b-38e64061f2fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@name='kode'])[2]</value>
      <webElementGuid>38e690b6-3ae5-4ffa-a7ce-450d182c31d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='online']/div/form/div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>5c119a78-54d6-4e1c-969b-0c3243bd1f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Barang'])[2]/following::select[1]</value>
      <webElementGuid>764f01b7-07db-4e12-b39a-2b0ad1ea1def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Barang'])[1]/following::select[1]</value>
      <webElementGuid>5a66cf11-7d59-4877-9acb-6cd703a8af34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga (per Hari)'])[2]/preceding::select[1]</value>
      <webElementGuid>154c4db5-588e-43d3-871e-6179e445786e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[2]/preceding::select[1]</value>
      <webElementGuid>c69b264a-6aa7-4a95-ae6b-28dfb457b42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>57ede78a-2a58-498b-bae6-ea3dbd4ac79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kode' and (text() = '--Pilih Barang--Carrier 35 Liter (20 unit)Carrier 45 Liter (19 unit)Carrier 60 Liter (23 unit)Carrier 80 Liter (10 unit)Kompor Besar (8 unit)Headlamp (50 unit)Lampu Tenda (29 unit)Nesting (63 unit)Kompor Portable Mini (17 unit)Gas HiCook (110 unit)Sepatu Tinggi Size 40 (10 unit)Sepatu Tinggi Size 41 (15 unit)Sepatu Tinggi Size 43 (15 unit)Sepatu Tinggi Size 42 (10 unit)Tas Slempang (15 unit)Tenda Kapasitas 2-3 Orang (60 unit)Tenda Double Layer Kapasitas 4-5 Orang (26 unit)Tenda Single Layer 4-5 Orang (17 unit)Tenda Kapasitas 7-8 Orang (15 unit)Tenda Kapasitas 8-10 Orang (20 unit)Tracking Pole (30 unit)Sleeping Bag (46 unit)Matras (36 unit)' or . = '--Pilih Barang--Carrier 35 Liter (20 unit)Carrier 45 Liter (19 unit)Carrier 60 Liter (23 unit)Carrier 80 Liter (10 unit)Kompor Besar (8 unit)Headlamp (50 unit)Lampu Tenda (29 unit)Nesting (63 unit)Kompor Portable Mini (17 unit)Gas HiCook (110 unit)Sepatu Tinggi Size 40 (10 unit)Sepatu Tinggi Size 41 (15 unit)Sepatu Tinggi Size 43 (15 unit)Sepatu Tinggi Size 42 (10 unit)Tas Slempang (15 unit)Tenda Kapasitas 2-3 Orang (60 unit)Tenda Double Layer Kapasitas 4-5 Orang (26 unit)Tenda Single Layer 4-5 Orang (17 unit)Tenda Kapasitas 7-8 Orang (15 unit)Tenda Kapasitas 8-10 Orang (20 unit)Tracking Pole (30 unit)Sleeping Bag (46 unit)Matras (36 unit)')]</value>
      <webElementGuid>6e5bc0eb-f294-46a7-8c7e-b961ab29e6b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
